2024-12-13 16:33:00,738 - INFO - Starting pipeline execution from 2023-01-01 to 2024-12-31.
2024-12-13 16:33:00,738 - INFO - Starting Dimensional Data Flow Execution ID: 022d475b-7939-4ea6-b0b8-e17ac07c42eb
2024-12-13 16:33:00,738 - ERROR - Table creation failed: "'SQL_SERVER' section not found in the configuration file."
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/pipeline_dimensional_data/tasks.py", line 29, in create_tables_task
    execute_sql_script_from_file(sql_file_path)
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 53, in execute_sql_script_from_file
    db_config = get_db_config(config_file)
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 30, in get_db_config
    raise KeyError("'SQL_SERVER' section not found in the configuration file.")
KeyError: "'SQL_SERVER' section not found in the configuration file."
2024-12-13 16:33:00,741 - ERROR - Execution 022d475b-7939-4ea6-b0b8-e17ac07c42eb failed: Table creation failed.
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/pipeline_dimensional_data/flow.py", line 51, in exec
    raise Exception("Table creation failed.")
Exception: Table creation failed.
2024-12-13 16:33:00,742 - INFO - Execution completed!
2024-12-13 16:33:00,742 - INFO - Final Pipeline Status: {'create_tables': {'success': False, 'error': '"\'SQL_SERVER\' section not found in the configuration file."'}, 'error': 'Table creation failed.'}
2024-12-13 16:33:45,460 - INFO - Starting pipeline execution from 2023-01-01 to 2024-12-31.
2024-12-13 16:33:45,460 - INFO - Starting Dimensional Data Flow Execution ID: 0a2e30f6-6ccf-4d58-9727-e34bdcee8ef6
2024-12-13 16:33:45,461 - INFO - Connecting to the database...
2024-12-13 16:33:45,738 - INFO - Connection established successfully.
2024-12-13 16:33:45,739 - INFO - Loaded SQL script from: infrastructure_initiation/dimensional_db_table_creation.sql
2024-12-13 16:33:45,739 - INFO - SQL script contains 12 statements.
2024-12-13 16:33:45,739 - DEBUG - Executing statement 1: USE ORDER_DDS...
2024-12-13 16:33:45,763 - INFO - Statement 1 executed successfully.
2024-12-13 16:33:45,763 - DEBUG - Executing statement 2: -- ===============================================...
2024-12-13 16:33:45,886 - ERROR - Error executing statement 2: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimCategories' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimCategories' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:33:45,887 - DEBUG - Executing statement 3: -- SCD1: Only current data is stored, with no hist...
2024-12-13 16:33:45,895 - ERROR - Error executing statement 3: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimCustomers' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimCustomers' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:33:45,895 - DEBUG - Executing statement 4: -- SCD2: Tracks historical changes by adding new r...
2024-12-13 16:33:45,900 - ERROR - Error executing statement 4: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimEmployees' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimEmployees' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:33:45,900 - DEBUG - Executing statement 5: -- SCD1 with Delete: Only current data is stored, ...
2024-12-13 16:33:45,906 - ERROR - Error executing statement 5: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimProducts' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimProducts' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:33:45,906 - DEBUG - Executing statement 6: -- SCD1: Only current data is stored, with no hist...
2024-12-13 16:33:45,911 - ERROR - Error executing statement 6: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimRegion' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimRegion' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:33:45,912 - DEBUG - Executing statement 7: -- SCD4: Historical snapshots are stored, with eac...
2024-12-13 16:33:45,914 - ERROR - Error executing statement 7: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimShippers' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimShippers' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:33:45,915 - DEBUG - Executing statement 8: -- SCD1 with Delete: Only current data is stored, ...
2024-12-13 16:33:45,917 - ERROR - Error executing statement 8: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimSuppliers' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimSuppliers' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:33:45,917 - DEBUG - Executing statement 9: -- SCD3: Tracks one historical version by keeping ...
2024-12-13 16:33:45,921 - ERROR - Error executing statement 9: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimTerritories' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimTerritories' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:33:45,921 - DEBUG - Executing statement 10: -- SCD4: Historical snapshots are stored, with eac...
2024-12-13 16:33:45,925 - ERROR - Error executing statement 10: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'Dim_SOR' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'Dim_SOR' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:33:45,926 - DEBUG - Executing statement 11: -- Dim_SOR: Used for tracking staging raw data and...
2024-12-13 16:33:45,932 - ERROR - Error executing statement 11: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'FactOrders' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'FactOrders' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:33:45,933 - DEBUG - Executing statement 12: -- FactOrders: Captures transactional data and lin...
2024-12-13 16:33:45,934 - INFO - Statement 12 executed successfully.
2024-12-13 16:33:45,934 - INFO - All statements executed successfully from: infrastructure_initiation/dimensional_db_table_creation.sql
2024-12-13 16:33:45,935 - INFO - Tables created successfully from: infrastructure_initiation/dimensional_db_table_creation.sql
2024-12-13 16:33:45,935 - INFO - Table creation completed successfully.
2024-12-13 16:33:46,028 - INFO - Data successfully ingested from: pipeline_dimensional_data/queries/update_fact.sql
2024-12-13 16:33:46,028 - INFO - Fact table ingestion completed successfully.
2024-12-13 16:33:46,057 - INFO - Faulty rows ingested from: pipeline_dimensional_data/queries/update_fact_error.sql
2024-12-13 16:33:46,057 - INFO - FactError table ingestion completed successfully.
2024-12-13 16:33:46,058 - INFO - Execution 0a2e30f6-6ccf-4d58-9727-e34bdcee8ef6 completed successfully!
2024-12-13 16:33:46,058 - INFO - Execution completed!
2024-12-13 16:33:46,058 - INFO - Final Pipeline Status: {'create_tables': {'success': True}, 'ingest_fact': {'success': True}, 'ingest_fact_error': {'success': True}}
2024-12-13 16:45:07,880 - INFO - Starting pipeline execution from 2023-01-01 to 2024-12-31.
2024-12-13 16:45:07,881 - INFO - Starting Dimensional Data Flow Execution ID: 6576e2a5-4af6-4599-828f-67e6d4b3e3f6
2024-12-13 16:45:07,882 - INFO - Connecting to the database...
2024-12-13 16:45:07,882 - INFO - Connection established successfully.
2024-12-13 16:45:07,883 - INFO - Loaded SQL script from: infrastructure_initiation/dimensional_db_table_creation.sql
2024-12-13 16:45:07,883 - INFO - SQL script contains 12 statements.
2024-12-13 16:45:07,883 - DEBUG - Executing statement 1: USE ORDER_DDS...
2024-12-13 16:45:07,887 - INFO - Statement 1 executed successfully.
2024-12-13 16:45:07,887 - DEBUG - Executing statement 2: -- ===============================================...
2024-12-13 16:45:07,892 - ERROR - Error executing statement 2: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimCategories' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimCategories' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:45:07,893 - DEBUG - Executing statement 3: -- SCD1: Only current data is stored, with no hist...
2024-12-13 16:45:07,901 - ERROR - Error executing statement 3: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimCustomers' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimCustomers' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:45:07,902 - DEBUG - Executing statement 4: -- SCD2: Tracks historical changes by adding new r...
2024-12-13 16:45:07,905 - ERROR - Error executing statement 4: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimEmployees' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimEmployees' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:45:07,905 - DEBUG - Executing statement 5: -- SCD1 with Delete: Only current data is stored, ...
2024-12-13 16:45:07,910 - ERROR - Error executing statement 5: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimProducts' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimProducts' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:45:07,911 - DEBUG - Executing statement 6: -- SCD1: Only current data is stored, with no hist...
2024-12-13 16:45:07,915 - ERROR - Error executing statement 6: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimRegion' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimRegion' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:45:07,916 - DEBUG - Executing statement 7: -- SCD4: Historical snapshots are stored, with eac...
2024-12-13 16:45:07,921 - ERROR - Error executing statement 7: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimShippers' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimShippers' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:45:07,921 - DEBUG - Executing statement 8: -- SCD1 with Delete: Only current data is stored, ...
2024-12-13 16:45:07,926 - ERROR - Error executing statement 8: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimSuppliers' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimSuppliers' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:45:07,927 - DEBUG - Executing statement 9: -- SCD3: Tracks one historical version by keeping ...
2024-12-13 16:45:07,933 - ERROR - Error executing statement 9: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimTerritories' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'DimTerritories' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:45:07,933 - DEBUG - Executing statement 10: -- SCD4: Historical snapshots are stored, with eac...
2024-12-13 16:45:07,939 - ERROR - Error executing statement 10: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'Dim_SOR' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'Dim_SOR' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:45:07,939 - DEBUG - Executing statement 11: -- Dim_SOR: Used for tracking staging raw data and...
2024-12-13 16:45:07,944 - ERROR - Error executing statement 11: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'FactOrders' in the database. (2714) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/Users/hrag03/Downloads/Business_Intelligence_Project/utils.py", line 82, in execute_sql_script_from_file
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'FactOrders' in the database. (2714) (SQLExecDirectW)")
2024-12-13 16:45:07,945 - DEBUG - Executing statement 12: -- FactOrders: Captures transactional data and lin...
2024-12-13 16:45:07,950 - INFO - Statement 12 executed successfully.
2024-12-13 16:45:07,950 - INFO - All statements executed successfully from: infrastructure_initiation/dimensional_db_table_creation.sql
2024-12-13 16:45:07,951 - INFO - Tables created successfully from: infrastructure_initiation/dimensional_db_table_creation.sql
2024-12-13 16:45:07,951 - INFO - Table creation completed successfully.
2024-12-13 16:45:07,959 - INFO - Data successfully ingested from: pipeline_dimensional_data/queries/update_fact.sql
2024-12-13 16:45:07,959 - INFO - Fact table ingestion completed successfully.
2024-12-13 16:45:07,966 - INFO - Faulty rows ingested from: pipeline_dimensional_data/queries/update_fact_error.sql
2024-12-13 16:45:07,966 - INFO - FactError table ingestion completed successfully.
2024-12-13 16:45:07,966 - INFO - Execution 6576e2a5-4af6-4599-828f-67e6d4b3e3f6 completed successfully!
2024-12-13 16:45:07,966 - INFO - Execution completed!
2024-12-13 16:45:07,967 - INFO - Final Pipeline Status: {'create_tables': {'success': True}, 'ingest_fact': {'success': True}, 'ingest_fact_error': {'success': True}}
2024-12-13 16:50:07,693 - INFO - Starting pipeline execution from 2023-01-01 to 2024-12-31.
2024-12-13 16:50:07,694 - INFO - Starting Dimensional Data Flow Execution ID: 4cbacf1a-87fb-4e84-b9f6-2e655991f32d
2024-12-13 16:50:07,694 - INFO - Connecting to the database...
2024-12-13 16:50:07,695 - INFO - Connection established successfully.
2024-12-13 16:50:07,695 - INFO - Loaded SQL script from: infrastructure_initiation/dimensional_db_table_creation.sql
2024-12-13 16:50:07,695 - INFO - SQL script contains 12 statements.
2024-12-13 16:50:07,696 - DEBUG - Executing statement 1: USE ORDER_DDS...
2024-12-13 16:50:07,698 - INFO - Statement 1 executed successfully.
2024-12-13 16:50:07,699 - DEBUG - Executing statement 2: -- ===============================================...
2024-12-13 16:50:07,720 - INFO - Statement 2 executed successfully.
2024-12-13 16:50:07,720 - DEBUG - Executing statement 3: -- SCD1: Only current data is stored, with no hist...
2024-12-13 16:50:07,733 - INFO - Statement 3 executed successfully.
2024-12-13 16:50:07,733 - DEBUG - Executing statement 4: -- SCD2: Tracks historical changes by adding new r...
2024-12-13 16:50:07,740 - INFO - Statement 4 executed successfully.
2024-12-13 16:50:07,740 - DEBUG - Executing statement 5: -- SCD1 with Delete: Only current data is stored, ...
2024-12-13 16:50:07,748 - INFO - Statement 5 executed successfully.
2024-12-13 16:50:07,748 - DEBUG - Executing statement 6: -- SCD1: Only current data is stored, with no hist...
2024-12-13 16:50:07,753 - INFO - Statement 6 executed successfully.
2024-12-13 16:50:07,753 - DEBUG - Executing statement 7: -- SCD4: Historical snapshots are stored, with eac...
2024-12-13 16:50:07,760 - INFO - Statement 7 executed successfully.
2024-12-13 16:50:07,761 - DEBUG - Executing statement 8: -- SCD1 with Delete: Only current data is stored, ...
2024-12-13 16:50:07,768 - INFO - Statement 8 executed successfully.
2024-12-13 16:50:07,769 - DEBUG - Executing statement 9: -- SCD3: Tracks one historical version by keeping ...
2024-12-13 16:50:07,777 - INFO - Statement 9 executed successfully.
2024-12-13 16:50:07,778 - DEBUG - Executing statement 10: -- SCD4: Historical snapshots are stored, with eac...
2024-12-13 16:50:07,783 - INFO - Statement 10 executed successfully.
2024-12-13 16:50:07,784 - DEBUG - Executing statement 11: -- Dim_SOR: Used for tracking staging raw data and...
2024-12-13 16:50:07,804 - INFO - Statement 11 executed successfully.
2024-12-13 16:50:07,804 - DEBUG - Executing statement 12: -- FactOrders: Captures transactional data and lin...
2024-12-13 16:50:07,806 - INFO - Statement 12 executed successfully.
2024-12-13 16:50:07,806 - INFO - All statements executed successfully from: infrastructure_initiation/dimensional_db_table_creation.sql
2024-12-13 16:50:07,806 - INFO - Tables created successfully from: infrastructure_initiation/dimensional_db_table_creation.sql
2024-12-13 16:50:07,806 - INFO - Table creation completed successfully.
2024-12-13 16:50:07,816 - INFO - Data successfully ingested from: pipeline_dimensional_data/queries/update_fact.sql
2024-12-13 16:50:07,816 - INFO - Fact table ingestion completed successfully.
2024-12-13 16:50:07,822 - INFO - Faulty rows ingested from: pipeline_dimensional_data/queries/update_fact_error.sql
2024-12-13 16:50:07,822 - INFO - FactError table ingestion completed successfully.
2024-12-13 16:50:07,822 - INFO - Execution 4cbacf1a-87fb-4e84-b9f6-2e655991f32d completed successfully!
2024-12-13 16:50:07,823 - INFO - Execution completed!
2024-12-13 16:50:07,823 - INFO - Final Pipeline Status: {'create_tables': {'success': True}, 'ingest_fact': {'success': True}, 'ingest_fact_error': {'success': True}}
2024-12-13 17:11:13,206 - INFO - Starting pipeline execution from 2023-01-01 to 2024-12-31.
2024-12-13 17:11:13,207 - INFO - Starting Dimensional Data Flow Execution ID: 89c06f1b-deab-405c-9a25-57dfcd64a23d
2024-12-13 17:11:13,208 - INFO - Connecting to the database...
2024-12-13 17:11:13,208 - INFO - Connection established successfully.
2024-12-13 17:11:13,210 - INFO - Loaded SQL script from: infrastructure_initiation/dimensional_db_table_creation.sql
2024-12-13 17:11:13,210 - INFO - SQL script contains 12 statements.
2024-12-13 17:11:13,210 - DEBUG - Executing statement 1: USE ORDER_DDS...
2024-12-13 17:11:13,212 - INFO - Statement 1 executed successfully.
2024-12-13 17:11:13,213 - DEBUG - Executing statement 2: -- ===============================================...
2024-12-13 17:11:13,221 - INFO - Statement 2 executed successfully.
2024-12-13 17:11:13,221 - DEBUG - Executing statement 3: -- SCD1: Only current data is stored, with no hist...
2024-12-13 17:11:13,228 - INFO - Statement 3 executed successfully.
2024-12-13 17:11:13,228 - DEBUG - Executing statement 4: -- SCD2: Tracks historical changes by adding new r...
2024-12-13 17:11:13,236 - INFO - Statement 4 executed successfully.
2024-12-13 17:11:13,236 - DEBUG - Executing statement 5: -- SCD1 with Delete: Only current data is stored, ...
2024-12-13 17:11:13,240 - INFO - Statement 5 executed successfully.
2024-12-13 17:11:13,241 - DEBUG - Executing statement 6: -- SCD1: Only current data is stored, with no hist...
2024-12-13 17:11:13,245 - INFO - Statement 6 executed successfully.
2024-12-13 17:11:13,245 - DEBUG - Executing statement 7: -- SCD4: Historical snapshots are stored, with eac...
2024-12-13 17:11:13,251 - INFO - Statement 7 executed successfully.
2024-12-13 17:11:13,251 - DEBUG - Executing statement 8: -- SCD1 with Delete: Only current data is stored, ...
2024-12-13 17:11:13,260 - INFO - Statement 8 executed successfully.
2024-12-13 17:11:13,260 - DEBUG - Executing statement 9: -- SCD3: Tracks one historical version by keeping ...
2024-12-13 17:11:13,268 - INFO - Statement 9 executed successfully.
2024-12-13 17:11:13,268 - DEBUG - Executing statement 10: -- SCD4: Historical snapshots are stored, with eac...
2024-12-13 17:11:13,277 - INFO - Statement 10 executed successfully.
2024-12-13 17:11:13,277 - DEBUG - Executing statement 11: -- Dim_SOR: Used for tracking staging raw data and...
2024-12-13 17:11:13,288 - INFO - Statement 11 executed successfully.
2024-12-13 17:11:13,289 - DEBUG - Executing statement 12: -- FactOrders: Captures transactional data and lin...
2024-12-13 17:11:13,290 - INFO - Statement 12 executed successfully.
2024-12-13 17:11:13,291 - INFO - All statements executed successfully from: infrastructure_initiation/dimensional_db_table_creation.sql
2024-12-13 17:11:13,291 - INFO - Tables created successfully from: infrastructure_initiation/dimensional_db_table_creation.sql
2024-12-13 17:11:13,291 - INFO - Table creation completed successfully.
2024-12-13 17:11:13,304 - INFO - Data successfully ingested from: pipeline_dimensional_data/queries/update_fact.sql
2024-12-13 17:11:13,305 - INFO - Fact table ingestion completed successfully.
2024-12-13 17:11:13,310 - INFO - Faulty rows ingested from: pipeline_dimensional_data/queries/update_fact_error.sql
2024-12-13 17:11:13,311 - INFO - FactError table ingestion completed successfully.
2024-12-13 17:11:13,311 - INFO - Execution 89c06f1b-deab-405c-9a25-57dfcd64a23d completed successfully!
2024-12-13 17:11:13,311 - INFO - Execution completed!
2024-12-13 17:11:13,311 - INFO - Final Pipeline Status: {'create_tables': {'success': True}, 'ingest_fact': {'success': True}, 'ingest_fact_error': {'success': True}}
2024-12-13 17:26:48,323 - INFO - Starting pipeline execution from 2023-01-01 to 2024-12-31.
2024-12-13 17:26:48,324 - INFO - Starting Dimensional Data Flow Execution ID: 507950e1-d8b8-4de6-876f-524d0389ac89
2024-12-13 17:26:48,325 - INFO - Connecting to the database...
2024-12-13 17:26:48,325 - INFO - Connection established successfully.
2024-12-13 17:26:48,327 - INFO - Loaded SQL script from: infrastructure_initiation/dimensional_db_table_creation.sql
2024-12-13 17:26:48,327 - INFO - SQL script contains 12 statements.
2024-12-13 17:26:48,327 - DEBUG - Executing statement 1: USE ORDER_DDS...
2024-12-13 17:26:48,329 - INFO - Statement 1 executed successfully.
2024-12-13 17:26:48,329 - DEBUG - Executing statement 2: -- ===============================================...
2024-12-13 17:26:48,335 - INFO - Statement 2 executed successfully.
2024-12-13 17:26:48,336 - DEBUG - Executing statement 3: -- SCD1: Only current data is stored, with no hist...
2024-12-13 17:26:48,341 - INFO - Statement 3 executed successfully.
2024-12-13 17:26:48,342 - DEBUG - Executing statement 4: -- SCD2: Tracks historical changes by adding new r...
2024-12-13 17:26:48,347 - INFO - Statement 4 executed successfully.
2024-12-13 17:26:48,347 - DEBUG - Executing statement 5: -- SCD1 with Delete: Only current data is stored, ...
2024-12-13 17:26:48,351 - INFO - Statement 5 executed successfully.
2024-12-13 17:26:48,352 - DEBUG - Executing statement 6: -- SCD1: Only current data is stored, with no hist...
2024-12-13 17:26:48,357 - INFO - Statement 6 executed successfully.
2024-12-13 17:26:48,357 - DEBUG - Executing statement 7: -- SCD4: Historical snapshots are stored, with eac...
2024-12-13 17:26:48,361 - INFO - Statement 7 executed successfully.
2024-12-13 17:26:48,361 - DEBUG - Executing statement 8: -- SCD1 with Delete: Only current data is stored, ...
2024-12-13 17:26:48,367 - INFO - Statement 8 executed successfully.
2024-12-13 17:26:48,367 - DEBUG - Executing statement 9: -- SCD3: Tracks one historical version by keeping ...
2024-12-13 17:26:48,371 - INFO - Statement 9 executed successfully.
2024-12-13 17:26:48,371 - DEBUG - Executing statement 10: -- SCD4: Historical snapshots are stored, with eac...
2024-12-13 17:26:48,377 - INFO - Statement 10 executed successfully.
2024-12-13 17:26:48,377 - DEBUG - Executing statement 11: -- Dim_SOR: Used for tracking staging raw data and...
2024-12-13 17:26:48,385 - INFO - Statement 11 executed successfully.
2024-12-13 17:26:48,385 - DEBUG - Executing statement 12: -- FactOrders: Captures transactional data and lin...
2024-12-13 17:26:48,387 - INFO - Statement 12 executed successfully.
2024-12-13 17:26:48,387 - INFO - All statements executed successfully from: infrastructure_initiation/dimensional_db_table_creation.sql
2024-12-13 17:26:48,387 - INFO - Tables created successfully from: infrastructure_initiation/dimensional_db_table_creation.sql
2024-12-13 17:26:48,387 - INFO - Table creation completed successfully.
2024-12-13 17:26:48,398 - INFO - Data successfully ingested from: pipeline_dimensional_data/queries/update_fact.sql
2024-12-13 17:26:48,398 - INFO - Fact table ingestion completed successfully.
2024-12-13 17:26:48,405 - INFO - Faulty rows ingested from: pipeline_dimensional_data/queries/update_fact_error.sql
2024-12-13 17:26:48,405 - INFO - FactError table ingestion completed successfully.
2024-12-13 17:26:48,405 - INFO - Execution 507950e1-d8b8-4de6-876f-524d0389ac89 completed successfully!
2024-12-13 17:26:48,405 - INFO - Execution completed!
2024-12-13 17:26:48,405 - INFO - Final Pipeline Status: {'create_tables': {'success': True}, 'ingest_fact': {'success': True}, 'ingest_fact_error': {'success': True}}
